name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: "0 9 * * 1,4" # Runs at 9:00 AM UTC every Monday and Thursday
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --production

      # Step 4: Ping Supabase
      - name: Ping Supabase
        env:
          # Mackdin Supabase project
          DATABASE_URL_MACKDIN: ${{ secrets.SUPABASE_DATABASE_URL_MACKDIN }}
          # Twitter Clone Supabase project
          DATABASE_URL_TWITTER_CLONE: ${{ secrets.DATABASE_URL_TWITTER_CLONE }}

        # Run the ping script
        run: npm run ping
